spring:
  application:
    name: tag-module
  datasource:
    url: jdbc:postgresql://localhost:5432/quizplatform
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083
  servlet:
    context-path: /

logging:
  level:
    com.quizplatform.modules.tag: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

tag:
  popular:
    cache-ttl-seconds: 3600
    max-items: 20