server:
  port: ${PORT:8083}

spring:
  application:
    name: battle-service
  
  # 데이터베이스 설정
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/quizplatform}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: battle_schema
        format_sql: true
        show_sql: false
  
  # Redis 설정
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    timeout: 10000
  
  # Kafka 설정
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# Eureka 클라이언트 설정
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true

# 로깅 설정
logging:
  level:
    root: INFO
    com.quizplatform.battle: DEBUG
    org.springframework.kafka: INFO 