server:
  port: 8083

spring:
  application:
    name: battle-service
    
  # 빈 재정의 허용
  main:
    allow-bean-definition-overriding: true
    
  # Swagger/OpenAPI 설정
  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      tags-sorter: alpha
      operations-sorter: alpha
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
    
  # 데이터베이스 설정
  datasource:
    url: jdbc:postgresql://postgres:5432/quiz_platform?currentSchema=battle_schema
    username: quizuser
    password: quizpass
    driver-class-name: org.postgresql.Driver
  
  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: battle_schema
        format_sql: true
        show_sql: false
  
  # Redis 설정
  redis:
    host: redis
    port: 6379
    timeout: 10000
  
  # Kafka 설정
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# JWT 설정
jwt:
  secret: ${JWT_SECRET:quizplatform_default_secret_key_change_in_production}
  expiration: ${JWT_EXPIRATION:86400000} # 24시간 (milliseconds)
  refreshExpiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7일 (milliseconds)

# Eureka 클라이언트 설정
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

# 로깅 설정
logging:
  level:
    root: INFO
    com.quizplatform.battle: DEBUG
    org.springframework.kafka: INFO 