version: '3.8'

services:
  # API 게이트웨이 서비스
  api-gateway:
    build: 
      context: .
      dockerfile: ./modules/api-gateway/Dockerfile
    container_name: quiz-api-gateway-dev
    ports:
      - "8080:8080"
      - "5080:5080"  # 디버깅 포트
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - REDIS_HOST=redis
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5080
    volumes:
      - ./modules/api-gateway/src:/workspace/app/src
      - ./modules/api-gateway/build.gradle:/workspace/app/build.gradle
      - maven-repo:/root/.m2
    depends_on:
      - redis
      - kafka
      - eureka-server
    networks:
      - quiz-network
    restart: unless-stopped

  # Eureka Server 서비스
  eureka-server:
    build: 
      context: .
      dockerfile: ./modules/eureka-server/Dockerfile
    container_name: quiz-eureka-server-dev
    ports:
      - "8761:8761"
      - "5761:5761"  # 디버깅 포트
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5761
    volumes:
      - ./modules/eureka-server:/workspace/app
      - maven-repo:/root/.m2
    networks:
      - quiz-network
    restart: unless-stopped

  # 유저 서비스
  user-service:
    build: 
      context: .
      dockerfile: ./modules/user/Dockerfile
    container_name: quiz-user-service-dev
    ports:
      - "8081:8081"
      - "5081:5081"  # 디버깅 포트
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5081
    volumes:
      - ./modules/user:/workspace/app
      - maven-repo:/root/.m2
    depends_on:
      - postgres
      - eureka-server
      - kafka
    networks:
      - quiz-network
    restart: unless-stopped

  # 퀴즈 서비스
  quiz-service:
    build: 
      context: .
      dockerfile: ./modules/quiz/Dockerfile
    container_name: quiz-quiz-service-dev
    ports:
      - "8082:8082"
      - "5082:5082"  # 디버깅 포트
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5082
    volumes:
      - ./modules/quiz:/workspace/app
      - maven-repo:/root/.m2
    depends_on:
      - postgres
      - eureka-server
      - elasticsearch
      - kafka
    networks:
      - quiz-network
    restart: unless-stopped

  # 배틀 서비스
  battle-service:
    build: 
      context: .
      dockerfile: ./modules/battle/Dockerfile
    container_name: quiz-battle-service-dev
    ports:
      - "8083:8083"
      - "5083:5083"  # 디버깅 포트
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5083
    volumes:
      - ./modules/battle:/workspace/app
      - maven-repo:/root/.m2
    depends_on:
      - postgres
      - redis
      - eureka-server
      - kafka
    networks:
      - quiz-network
    restart: unless-stopped

  # PostgreSQL 데이터베이스 서비스
  postgres:
    image: postgres:15-alpine
    container_name: quiz-postgres-dev
    environment:
      POSTGRES_DB: quiz_platform
      POSTGRES_USER: quizuser
      POSTGRES_PASSWORD: quizpass
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - quiz-network
    restart: unless-stopped

  # Redis 캐시 서비스
  redis:
    image: redis:7-alpine
    container_name: quiz-redis-dev
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data_dev:/data
    networks:
      - quiz-network
    restart: unless-stopped

  # Elasticsearch 검색 엔진
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: quiz-elasticsearch-dev
    environment:
      - node.name=quiz-es01
      - cluster.name=quiz-es-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data_dev:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - quiz-network
    restart: unless-stopped

  # Zookeeper 서비스
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: quiz-zookeeper-dev
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data_dev:/var/lib/zookeeper/data
    networks:
      - quiz-network
    restart: unless-stopped

  # Kafka 서비스
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: quiz-kafka-dev
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
      - kafka_data_dev:/var/lib/kafka/data
    networks:
      - quiz-network
    restart: unless-stopped

volumes:
  postgres_data_dev:
  redis_data_dev:
  elasticsearch_data_dev:
  zookeeper_data_dev:
  kafka_data_dev:
  maven-repo:

networks:
  quiz-network:
    driver: bridge 