apiVersion: v1
kind: Secret
metadata:
  name: quiz-app-secret
  namespace: default

type: Opaque
stringData:
  POSTGRES_USER: "quizuser"
  POSTGRES_PASSWORD: "quizpass"
  JWT_SECRET: "quizplatform_default_secret_key_change_in_production"
