apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-service
  labels:
    app: quiz-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-service
  template:
    metadata:
      labels:
        app: quiz-service
    spec:
      containers:
      - name: quiz-service
        image: example/quiz-service:latest
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: quiz-app-config
              key: SPRING_PROFILES_ACTIVE
        - name: EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: quiz-app-config
              key: EUREKA_URL
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres:5432/quiz_platform?currentSchema=quiz_schema"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: quiz-app-secret
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: quiz-app-secret
              key: POSTGRES_PASSWORD
        - name: SPRING_ELASTICSEARCH_REST_URIS
          valueFrom:
            configMapKeyRef:
              name: quiz-app-config
              key: SPRING_ELASTICSEARCH_REST_URIS
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: quiz-app-config
              key: KAFKA_BOOTSTRAP_SERVERS
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-service
spec:
  selector:
    app: quiz-service
  ports:
  - port: 8082
    targetPort: 8082
