spring:
  application:
    name: quiz-module
  datasource:
    url: jdbc:postgresql://localhost:5432/quizplatform
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

server:
  port: 8082
  servlet:
    context-path: /

logging:
  level:
    com.quizplatform.modules.quiz: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

quiz:
  daily:
    generation-cron: "0 0 0 * * ?" # 매일 자정에 일일 퀴즈 생성
  recommendation:
    max-items: 10
    refresh-interval-minutes: 30