server:
  port: 8761

spring:
  security:
    user:
      name: eureka
      password: eureka

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false 