server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/quiz_platform
    username: quizuser
    password: quizpass
    driver-class-name: org.postgresql.Driver
  
  elasticsearch:
    rest:
      uris: http://elasticsearch:9200

  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: quiz-service
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer 