server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/quiz_platform
    username: quizuser
    password: quizpass
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: user-service
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer 