spring:
  application:
    name: battle-service
  
  datasource:
    url: jdbc:mysql://localhost:3306/quizplatform_battle?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: battle-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.quizplatform.*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8082
  servlet:
    context-path: /

# 다른 서비스 URL 설정
services:
  quiz-service-url: http://localhost:8081
  user-service-url: http://localhost:8080

# 로깅 설정
logging:
  level:
    com.quizplatform.battle: DEBUG
    org.hibernate.SQL: DEBUG
