spring:
  application:
    name: quiz-service
  datasource:
    url: jdbc:mysql://localhost:3306/quizplatform?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    consumer:
      group-id: quiz-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: ${SERVER_PORT:8082}

logging:
  level:
    com.quizplatform.quiz: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.springframework.kafka: INFO

# 애플리케이션 특정 설정
app:
  kafka:
    topics:
      quiz-events: quiz-events
      quiz-completed-events: quiz-completed-events
      high-score-events: high-score-events
      user-events: user-events
      achievement-events: achievement-events
    group-id: quiz-service