server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: user-service
    
  # Swagger/OpenAPI 설정
  springdoc:
    api-docs:
      path: /v3/api-docs
      enabled: true
      groups:
        enabled: true
    swagger-ui:
      path: /swagger-ui.html
      tags-sorter: alpha
      operations-sorter: alpha
      disable-swagger-default-url: true
      use-root-path: true
      display-request-duration: true
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
    paths-to-match: /**
    group-configs:
      - group: users
        paths-to-match: /**
  
  # 데이터베이스 설정
  datasource:
    url: jdbc:postgresql://postgres:5432/quiz_platform?currentSchema=user_schema
    username: quizuser
    password: quizpass
    driver-class-name: org.postgresql.Driver
  
  # JPA 설정  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: user_schema
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  # Kafka 설정
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: user-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.quizplatform.*
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# JWT 설정
jwt:
  secret: ${JWT_SECRET:quizplatform_default_secret_key_change_in_production}
  expiration: ${JWT_EXPIRATION:86400000} # 24시간 (milliseconds)
  refreshExpiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7일 (milliseconds)

# Eureka 클라이언트 설정
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
    metadata-map:
      group: users
      swagger-url: /v3/api-docs

# 로깅 설정
logging:
  level:
    com.quizplatform: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.kafka: INFO
    org.springframework.security: DEBUG
    org.springdoc: DEBUG 
