server:
  port: 8081

spring:
  application:
    name: user-service
  
  # 데이터베이스 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/quiz_platform
    username: quizuser
    password: quizpass
    driver-class-name: org.postgresql.Driver
  
  # JPA 설정  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  # Kafka 설정
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-service
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# Eureka 클라이언트 설정
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# 로깅 설정
logging:
  level:
    root: INFO
    com.quizplatform: DEBUG
    org.hibernate.SQL: DEBUG 