server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
    
  # 데이터소스 자동 구성 비활성화
  autoconfigure:
    exclude: 
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  
  # Redis 설정
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      client-name: ${spring.application.name}
      connect-timeout: 5s
      

  
  # Swagger/OpenAPI 설정
  springdoc:
    api-docs:
      enabled: true
      path: /v3/api-docs
    swagger-ui:
      enabled: true
      path: /swagger-ui.html
      configUrl: /v3/api-docs/swagger-config
      urls:
        - url: /v3/api-docs/api-gateway
          name: API Gateway
        - url: /v3/api-docs/users
          name: User Service 
        - url: /v3/api-docs/quizzes
          name: Quiz Service
        - url: /v3/api-docs/battles
          name: Battle Service
      use-root-path: true
      urls-primary-name: API Gateway # 기본으로 표시될 API 문서
      layout: BaseLayout
      groups-order: DESC
      operationsSorter: alpha
      tagsSorter: alpha
      display-request-duration: true
      deep-linking: true
      persistent-authorization: true
      disable-swagger-default-url: false
      supported-submit-methods: ["get", "put", "post", "delete", "options", "head", "patch", "trace"]
      try-it-out-enabled: true
    # API 그룹 기본 포함 여부 설정
    group-configs:
      - group: api-gateway
        paths-to-match: /api/gateway/**
      - group: auth
        paths-to-match: /api/auth/** 
      - group: users
        paths-to-match: /api/users/**
      - group: quizzes
        paths-to-match: /api/quizzes/**
      - group: battles
        paths-to-match: /api/battles/**
    show-actuator: true
    cache:
      disabled: true
    
  cloud:
    gateway:
      routes:
        # 마이크로서비스 API 라우팅
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<path>.*), /$\{path}
            
        - id: quiz-service
          uri: lb://quiz-service
          predicates:
            - Path=/api/quizzes/**
          filters:
            - RewritePath=/api/quizzes/(?<path>.*), /$\{path}
            
        - id: battle-service
          uri: lb://battle-service
          predicates:
            - Path=/api/battles/**
          filters:
            - RewritePath=/api/battles/(?<path>.*), /$\{path}
            
        # Swagger 문서 라우팅
        - id: user-openapi
          uri: lb://user-service
          predicates:
            - Path=/v3/api-docs/users/**
          filters:
            - RewritePath=/v3/api-docs/users/(?<path>.*), /v3/api-docs/$\{path}
            - RewritePath=/v3/api-docs/users$, /v3/api-docs
          metadata:
            response-timeout: 10000
            connect-timeout: 10000

        - id: quiz-openapi
          uri: lb://quiz-service
          predicates:
            - Path=/v3/api-docs/quizzes/**
          filters:
            - RewritePath=/v3/api-docs/quizzes/(?<path>.*), /v3/api-docs/$\{path}
            - RewritePath=/v3/api-docs/quizzes$, /v3/api-docs
          metadata:
            response-timeout: 10000
            connect-timeout: 10000

        - id: battle-openapi
          uri: lb://battle-service
          predicates:
            - Path=/v3/api-docs/battles/**
          filters:
            - RewritePath=/v3/api-docs/battles/(?<path>.*), /v3/api-docs/$\{path}
            - RewritePath=/v3/api-docs/battles$, /v3/api-docs
          metadata:
            response-timeout: 10000
            connect-timeout: 10000

        # API Gateway 자체 OpenAPI 문서
        - id: gateway-openapi
          uri: forward:/v3/api-docs
          predicates:
            - Path=/v3/api-docs/api-gateway
          filters:
            - SetPath=/v3/api-docs
        
        # Swagger UI 리소스 라우팅
        - id: openapi-swagger-ui
          uri: forward:/swagger-ui
          predicates:
            - Path=/swagger-ui/**
          filters:
            - RemoveRequestHeader=Cookie
          order: -10000
            
        - id: openapi-api-docs
          uri: forward:/v3/api-docs
          predicates:
            - Path=/v3/api-docs
          filters:
            - RemoveRequestHeader=Cookie
            - SetPath=/v3/api-docs
          order: -10000
            
        - id: swagger-ui-redirect
          uri: forward:/swagger-ui/index.html
          predicates:
            - Path=/swagger-ui.html
          filters:
            - RemoveRequestHeader=Cookie
          order: -10000
            
        # Swagger UI 리소스 라우팅
        - id: swagger-webjars
          uri: forward:/webjars
          predicates:
            - Path=/webjars/**
          filters:
            - RemoveRequestHeader=Cookie
          order: -10000
            
        # 루트 경로를 Swagger UI로 리디렉션
        - id: swagger-root
          uri: forward:/swagger-ui/index.html
          predicates:
            - Path=/
      
      # 서비스 발견 관련 설정
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          
      # 레이트 리미팅 설정
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 20
            redis-rate-limiter.burstCapacity: 40
            redis-rate-limiter.requestedTokens: 1
            
  # Kafka 설정
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    
# JWT 설정
jwt:
  secret: ${JWT_SECRET:quizplatform_default_secret_key_change_in_production}
  expiration: ${JWT_EXPIRATION:86400000} # 24시간 (milliseconds)
  refreshExpiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7일 (milliseconds)
    
# Eureka 클라이언트 설정
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE:http://eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    
# 로깅 설정
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.security: TRACE
    reactor.netty: DEBUG
    org.springdoc: TRACE
    com.quizplatform: DEBUG
    
# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always
