server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  main:
    web-application-type: reactive
    
  # 데이터소스 자동 구성 비활성화
  autoconfigure:
    exclude: 
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  
  # Redis 설정
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      client-name: ${spring.application.name}
      connect-timeout: 5s
  
  # Swagger/OpenAPI 설정
  springdoc:
    api-docs:
      enabled: true
      path: /api-docs
    swagger-ui:
      enabled: true
      path: /swagger-ui.html
      config-url: /api-docs/swagger-config
      urls:
        - url: /api-docs
          name: API Gateway
        - url: /users/v3/api-docs
          name: User Service
        - url: /battles/v3/api-docs
          name: Battle Service
        - url: /quizzes/v3/api-docs
          name: Quiz Service
      disable-swagger-default-url: true
      use-root-path: true
      url: /swagger-ui/index.html
  
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<path>.*), /$\{path}
            
        - id: quiz-service
          uri: lb://quiz-service
          predicates:
            - Path=/api/quizzes/**
          filters:
            - RewritePath=/api/quizzes/(?<path>.*), /$\{path}
            
        - id: battle-service
          uri: lb://battle-service
          predicates:
            - Path=/api/battles/**
          filters:
            - RewritePath=/api/battles/(?<path>.*), /$\{path}
            
        # Swagger API 문서 접근을 위한 경로 수정
        - id: user-service-api-docs
          uri: lb://user-service
          predicates:
            - Path=/users/v3/api-docs/**
          filters:
            - RewritePath=/users/v3/api-docs/(?<path>.*), /v3/api-docs/$\{path}
            
        - id: battle-service-api-docs
          uri: lb://battle-service
          predicates:
            - Path=/battles/v3/api-docs/**
          filters:
            - RewritePath=/battles/v3/api-docs/(?<path>.*), /v3/api-docs/$\{path}
            
        - id: quiz-service-api-docs
          uri: lb://quiz-service
          predicates:
            - Path=/quizzes/v3/api-docs/**
          filters:
            - RewritePath=/quizzes/v3/api-docs/(?<path>.*), /v3/api-docs/$\{path}
            
        # Swagger UI 웹자(webjars) 관련 경로 추가
        - id: swagger-webjars
          uri: forward:/webjars
          predicates:
            - Path=/webjars/**
          
        # 스웨거 UI 직접 접근 경로
        - id: swagger-ui-direct
          uri: forward:/swagger-ui
          predicates:
            - Path=/swagger-ui/**
            
        # API-Docs 직접 접근 경로
        - id: api-docs-direct
          uri: forward:/api-docs
          predicates:
            - Path=/api-docs/**
            
        # 추가: Swagger UI 인덱스 페이지 직접 접근
        - id: swagger-ui-index
          uri: forward:/swagger-ui.html
          predicates:
            - Path=/swagger-ui.html
            
        # 추가: Root 경로에서 Swagger 리다이렉트
        - id: swagger-root-redirect
          uri: forward:/swagger-ui.html
          predicates:
            - Path=/
            
        # v3/api-docs 접근 경로
        - id: api-docs-v3
          uri: forward:/api-docs
          predicates:
            - Path=/v3/api-docs/**
            
  # Kafka 설정
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    
# JWT 설정
jwt:
  secret: ${JWT_SECRET:quizplatform_default_secret_key_change_in_production}
  expiration: ${JWT_EXPIRATION:86400000} # 24시간 (milliseconds)
  refreshExpiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7일 (milliseconds)
    
# Eureka 클라이언트 설정
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE:http://eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    
# 로깅 설정
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.security: DEBUG
    reactor.netty: DEBUG
    org.springdoc: DEBUG
    
# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always
