server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  main:
    web-application-type: reactive
    
  # 데이터소스 자동 구성 비활성화
  autoconfigure:
    exclude: 
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  
  # OAuth2 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-client-secret}
            scope:
              - email
              - profile
          github:
            client-id: ${GITHUB_CLIENT_ID:your-github-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:your-github-client-secret}
            scope:
              - user:email
              - read:user
  
  # Redis 설정
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      client-name: ${spring.application.name}
      connect-timeout: 5s
  
  # Swagger/OpenAPI 설정
  springdoc:
    api-docs:
      enabled: true
      path: /api-docs
    swagger-ui:
      enabled: true
      path: /swagger-ui.html
      config-url: /api-docs/swagger-config
      urls:
        - url: /api-docs
          name: API Gateway
        - url: /users/v3/api-docs
          name: User Service
        - url: /battles/v3/api-docs
          name: Battle Service
        - url: /quizzes/v3/api-docs
          name: Quiz Service
      disable-swagger-default-url: true
      use-root-path: true
    
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<path>.*), /$\{path}
            
        - id: quiz-service
          uri: lb://quiz-service
          predicates:
            - Path=/api/quizzes/**
          filters:
            - RewritePath=/api/quizzes/(?<path>.*), /$\{path}
            
        - id: battle-service
          uri: lb://battle-service
          predicates:
            - Path=/api/battles/**
          filters:
            - RewritePath=/api/battles/(?<path>.*), /$\{path}
            
        # Swagger API 문서 접근을 위한 경로 수정
        - id: user-service-api-docs
          uri: lb://user-service
          predicates:
            - Path=/users/v3/api-docs/**
          filters:
            - RewritePath=/users/v3/api-docs/(?<path>.*), /v3/api-docs/$\{path}
            
        - id: battle-service-api-docs
          uri: lb://battle-service
          predicates:
            - Path=/battles/v3/api-docs/**
          filters:
            - RewritePath=/battles/v3/api-docs/(?<path>.*), /v3/api-docs/$\{path}
            
        - id: quiz-service-api-docs
          uri: lb://quiz-service
          predicates:
            - Path=/quizzes/v3/api-docs/**
          filters:
            - RewritePath=/quizzes/v3/api-docs/(?<path>.*), /v3/api-docs/$\{path}
            
        # Swagger 관련 경로 설정
        - id: swagger-ui
          uri: forward:/swagger-ui
          predicates:
            - Path=/swagger-ui/**
            
        - id: swagger-api-docs
          uri: forward:/v3/api-docs
          predicates:
            - Path=/v3/api-docs/**
            
        - id: swagger-webjars
          uri: forward:/webjars
          predicates:
            - Path=/webjars/**
            
        - id: api-docs-direct
          uri: forward:/api-docs
          predicates:
            - Path=/api-docs/**
        
        - id: swagger-ui-html
          uri: forward:/swagger-ui/index.html
          predicates:
            - Path=/swagger-ui.html
            
        - id: swagger-root
          uri: forward:/swagger-ui/index.html
          predicates:
            - Path=/
      
      # 레이트 리미팅 설정
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 20
            redis-rate-limiter.burstCapacity: 40
            redis-rate-limiter.requestedTokens: 1
            
  # Kafka 설정
  kafka:
    bootstrap-servers: localhost:9092
    
# JWT 설정
jwt:
  secret: ${JWT_SECRET:quizplatform_default_secret_key_change_in_production}
  expiration: ${JWT_EXPIRATION:86400000} # 24시간 (milliseconds)
  refreshExpiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7일 (milliseconds)
    
# Eureka 클라이언트 설정
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    
# 로깅 설정
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.security: DEBUG
    reactor.netty: DEBUG
    
# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always
